import React, { useState } from 'react';
import {
  IntegrationWorkflow,
  WorkflowNode,
  ConnectorPlugin,
  StepLog
} from '../types';
import {
  GitFork,
  Play,
  Sparkles,
  Zap,
  ArrowRight,
  Bot,
  Filter,
  CheckCircle2,
  AlertCircle,
  Clock,
  Layers,
  Code2,
  Plus,
  RotateCw,
  Server
} from 'lucide-react';

interface WorkflowOrchestratorProps {
  workflows: IntegrationWorkflow[];
  connectors: ConnectorPlugin[];
  onExecuteWorkflow: (workflowId: string, customPayload: any) => Promise<any>;
  onCreateWorkflow: (wf: IntegrationWorkflow) => void;
}

export const WorkflowOrchestrator: React.FC<WorkflowOrchestratorProps> = ({
  workflows,
  connectors,
  onExecuteWorkflow,
  onCreateWorkflow
}) => {
  const [selectedWorkflowId, setSelectedWorkflowId] = useState<string>(workflows[0]?.id || '');
  const [testPayloadText, setTestPayloadText] = useState<string>(
    JSON.stringify(
      {
        From: '+14155552671',
        Body: 'CRITICAL ALERT: Enterprise cluster DB disk usage reached 98%',
        CustomerRegion: 'US-West-1',
        Severity: 'P1'
      },
      null,
      2
    )
  );

  const [isRunningTest, setIsRunningTest] = useState(false);
  const [testResult, setTestResult] = useState<any>(null);
  const [aiPrompt, setAiPrompt] = useState('');
  const [isAiGenerating, setIsAiGenerating] = useState(false);
  const [aiError, setAiError] = useState<string | null>(null);

  const activeWorkflow = workflows.find((w) => w.id === selectedWorkflowId) || workflows[0];

  const handleRunTest = async () => {
    if (!activeWorkflow) return;
    setIsRunningTest(true);
    setTestResult(null);

    try {
      let parsedPayload = {};
      try {
        parsedPayload = JSON.parse(testPayloadText);
      } catch {
        parsedPayload = { rawBody: testPayloadText };
      }

      const result = await onExecuteWorkflow(activeWorkflow.id, parsedPayload);
      setTestResult(result);
    } catch (err: any) {
      setTestResult({ error: err.message || 'Execution test failed' });
    } finally {
      setIsRunningTest(false);
    }
  };

  const handleAiSuggestWorkflow = async () => {
    if (!aiPrompt.trim()) return;
    setIsAiGenerating(true);
    setAiError(null);

    try {
      const res = await fetch('/api/gemini/suggest-workflow', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ useCase: aiPrompt })
      });

      const data = await res.json();
      if (!res.ok) throw new Error(data.details || data.error || 'Failed to generate workflow');

      const newWf: IntegrationWorkflow = {
        id: `wf_${Date.now().toString(36)}`,
        name: data.name || 'AI Designed CPaaS Workflow',
        description: data.description || 'Generated by Gemini AI Architect',
        status: 'ACTIVE',
        triggerConnectorId: connectors[0]?.id || 'conn_twilio',
        triggerEvent: 'inbound.event',
        executionMode: 'ASYNC_QUEUE',
        retryPolicy: { maxAttempts: 3, backoffSeconds: 5 },
        totalExecutions: 0,
        successRate: 100,
        nodes: (data.nodes || []).map((n: any, idx: number) => ({
          id: n.id || `node_${idx + 1}`,
          title: n.title || 'Workflow Step',
          type: (n.type as any) || 'TRANSFORM',
          config: { aiPromptTemplate: n.description }
        }))
      };

      onCreateWorkflow(newWf);
      setSelectedWorkflowId(newWf.id);
      setAiPrompt('');
    } catch (err: any) {
      setAiError(err.message);
    } finally {
      setIsAiGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* AI Workflow Architect Header Bar */}
      <div className="bg-slate-800 p-5 rounded-xl border border-slate-700 shadow-xs text-white">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-indigo-600 rounded-lg text-white font-bold">
              <Bot className="w-6 h-6" />
            </div>
            <div>
              <h2 className="font-bold text-slate-100 text-sm flex items-center gap-2">
                Gemini AI Workflow Architect
                <span className="px-2 py-0.5 text-[10px] font-mono bg-slate-700 text-indigo-300 rounded font-semibold">
                  gemini-3.6-flash
                </span>
              </h2>
              <p className="text-xs text-slate-300 font-sans">
                Describe an enterprise CPaaS integration requirement to auto-generate sequence nodes & payload transformers.
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2 flex-1 max-w-xl">
            <input
              type="text"
              placeholder="e.g. Inbound WhatsApp order status -> SAP ERP lookup -> SMS tracking notification if delayed"
              value={aiPrompt}
              onChange={(e) => setAiPrompt(e.target.value)}
              className="w-full bg-slate-900 border border-slate-700 rounded-lg px-3 py-2 text-xs text-slate-100 focus:outline-none focus:border-indigo-500 font-medium placeholder:text-slate-500"
            />
            <button
              onClick={handleAiSuggestWorkflow}
              disabled={isAiGenerating || !aiPrompt.trim()}
              className="px-4 py-2 text-xs font-semibold bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg transition-colors flex items-center space-x-1.5 cursor-pointer whitespace-nowrap disabled:opacity-50"
            >
              <Sparkles className={`w-3.5 h-3.5 ${isAiGenerating ? 'animate-spin' : ''}`} />
              <span>{isAiGenerating ? 'Designing...' : 'Auto-Build'}</span>
            </button>
          </div>
        </div>

        {aiError && (
          <div className="mt-3 text-xs text-rose-300 bg-rose-950/40 p-2 rounded border border-rose-500/30">
            {aiError}
          </div>
        )}
      </div>

      {/* Main Orchestration Canvas Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Workflows List & Topology */}
        <div className="lg:col-span-2 space-y-6">
          {/* Workflow Selector Tabs */}
          <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-xs">
            <div className="flex items-center justify-between mb-3">
              <h3 className="font-bold text-slate-800 text-xs uppercase tracking-wider flex items-center gap-1.5">
                <GitFork className="w-4 h-4 text-indigo-600" />
                Active CPaaS Workflows ({workflows.length})
              </h3>
            </div>

            <div className="flex flex-col space-y-2">
              {workflows.map((wf) => {
                const isSelected = wf.id === activeWorkflow?.id;
                return (
                  <button
                    key={wf.id}
                    onClick={() => {
                      setSelectedWorkflowId(wf.id);
                      setTestResult(null);
                    }}
                    className={`p-3.5 rounded-xl text-left transition-all cursor-pointer border ${
                      isSelected
                        ? 'bg-indigo-50/80 border-indigo-300 text-slate-900 shadow-xs'
                        : 'bg-slate-50 border-slate-200 text-slate-600 hover:bg-slate-100 hover:text-slate-900'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-xs text-slate-800">{wf.name}</span>
                      <span className="px-2.5 py-0.5 text-[10px] font-mono bg-emerald-50 text-emerald-700 border border-emerald-200 rounded-full font-bold">
                        {wf.executionMode}
                      </span>
                    </div>
                    <p className="text-[11px] text-slate-500 mt-1 line-clamp-1">{wf.description}</p>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Workflow Nodes Visual Topology Canvas */}
          {activeWorkflow && (
            <div className="bg-white border border-slate-200 rounded-xl p-5 space-y-4 shadow-xs">
              <div className="flex items-center justify-between border-b border-slate-200 pb-3">
                <div>
                  <h3 className="font-bold text-slate-800 text-sm">{activeWorkflow.name} Topology</h3>
                  <p className="text-xs text-slate-500">{activeWorkflow.nodes.length} Orchestration Steps</p>
                </div>

                <div className="flex items-center space-x-3 text-xs font-mono text-slate-500">
                  <span>Executions: <strong className="text-slate-800">{activeWorkflow.totalExecutions}</strong></span>
                  <span>•</span>
                  <span>Success: <strong className="text-emerald-600">{activeWorkflow.successRate}%</strong></span>
                </div>
              </div>

              {/* Node Sequence Chain */}
              <div className="space-y-3 relative py-2">
                {activeWorkflow.nodes.map((node, index) => {
                  const targetConn = connectors.find((c) => c.id === node.connectorId);

                  return (
                    <div key={node.id} className="relative">
                      {/* Connecting Line */}
                      {index > 0 && (
                        <div className="w-0.5 h-4 bg-indigo-300 mx-auto -mt-2 mb-1" />
                      )}

                      <div className="bg-slate-50 border border-slate-200 hover:border-indigo-300 p-4 rounded-xl flex items-start justify-between transition-colors shadow-xs">
                        <div className="flex items-start space-x-3">
                          <div className="w-6 h-6 rounded-md bg-indigo-600 text-white flex items-center justify-center font-mono text-xs font-bold shrink-0 mt-0.5 shadow-xs">
                            {index + 1}
                          </div>

                          <div>
                            <div className="flex items-center space-x-2">
                              <h4 className="font-bold text-slate-800 text-xs">{node.title}</h4>
                              <span className="px-2 py-0.2 text-[9px] font-mono uppercase bg-slate-200 text-slate-700 rounded font-bold">
                                {node.type}
                              </span>
                              {targetConn && (
                                <span className="text-[10px] text-indigo-700 font-bold bg-indigo-50 px-2 py-0.5 rounded border border-indigo-200">
                                  {targetConn.name}
                                </span>
                              )}
                            </div>

                            {/* Node Configuration Code Preview */}
                            {node.config.aiPromptTemplate && (
                              <div className="mt-2 text-[11px] text-slate-700 font-mono bg-white p-2.5 rounded-lg border border-slate-200">
                                <span className="text-indigo-600 font-bold">AI Prompt: </span>
                                {node.config.aiPromptTemplate}
                              </div>
                            )}

                            {node.config.conditionExpression && (
                              <div className="mt-2 text-[11px] text-amber-800 font-mono bg-amber-50/50 p-2.5 rounded-lg border border-amber-200">
                                <span className="text-amber-700 font-bold">IF: </span>
                                {node.config.conditionExpression}
                              </div>
                            )}

                            {node.config.fieldMappings && (
                              <div className="mt-2 text-[10px] text-slate-700 font-mono bg-white p-2.5 rounded-lg border border-slate-200">
                                {Object.entries(node.config.fieldMappings).map(([k, v]) => (
                                  <div key={k}>
                                    <span className="text-slate-500 font-bold">{k}:</span>{' '}
                                    <span className="text-indigo-600">{v}</span>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        </div>

                        <div className="text-[10px] font-mono text-slate-400 uppercase font-bold">
                          STEP #{index + 1}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        {/* Right Column: Interactive Test Runner Console */}
        <div className="space-y-6">
          <div className="bg-white border border-slate-200 rounded-xl p-5 space-y-4 shadow-xs">
            <div className="flex items-center justify-between border-b border-slate-200 pb-3">
              <h3 className="font-bold text-slate-800 text-xs uppercase tracking-wider flex items-center gap-1.5">
                <Zap className="w-4 h-4 text-indigo-600" />
                Pipeline Test Execution Console
              </h3>
            </div>

            <div>
              <label className="block text-slate-700 text-xs font-semibold mb-1">
                Input Event Payload (JSON)
              </label>
              <textarea
                rows={6}
                value={testPayloadText}
                onChange={(e) => setTestPayloadText(e.target.value)}
                className="w-full bg-slate-900 border border-slate-800 rounded-lg p-3 text-xs font-mono text-indigo-300 focus:outline-none focus:border-indigo-500"
              />
            </div>

            <button
              onClick={handleRunTest}
              disabled={isRunningTest || !activeWorkflow}
              className="w-full py-2.5 text-xs font-bold bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg transition-colors flex items-center justify-center space-x-2 cursor-pointer disabled:opacity-50 shadow-xs"
            >
              <Play className={`w-4 h-4 fill-current ${isRunningTest ? 'animate-spin' : ''}`} />
              <span>{isRunningTest ? 'Executing Sequence Steps...' : 'Execute Test Run'}</span>
            </button>

            {/* Step Logs Execution Results */}
            {testResult && (
              <div className="mt-4 pt-4 border-t border-slate-200 space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-slate-800 flex items-center gap-1">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    Trace: <span className="font-mono text-indigo-600">{testResult.traceId}</span>
                  </span>
                  <span className="text-[11px] font-mono text-slate-500 font-bold">
                    {testResult.totalDurationMs} ms
                  </span>
                </div>

                <div className="space-y-2 max-h-64 overflow-y-auto pr-1">
                  {(testResult.stepLogs || []).map((step: StepLog, idx: number) => (
                    <div
                      key={idx}
                      className="bg-slate-900 p-2.5 rounded-lg border border-slate-800 text-xs font-mono text-slate-200"
                    >
                      <div className="flex items-center justify-between text-[11px]">
                        <span className="font-bold text-slate-100">{step.nodeTitle}</span>
                        <span className="text-emerald-400 font-bold">{step.durationMs}ms</span>
                      </div>
                      {step.output && (
                        <pre className="mt-1 text-[10px] text-cyan-300 bg-slate-950 p-1.5 rounded overflow-x-auto">
                          {JSON.stringify(step.output, null, 2)}
                        </pre>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
